table lojas
	lineageTag: d8e8b26b-a3ff-4df7-96ef-c93d88263ca5

	column codigo_loja
		dataType: string
		lineageTag: a27f303d-cc97-4f9a-9b04-6194352d2ec9
		summarizeBy: none
		sourceColumn: codigo_loja

		annotation SummarizationSetBy = Automatic

	column nome_loja
		dataType: string
		lineageTag: eba41191-276d-4185-b373-5d0bdd9664e3
		summarizeBy: none
		sourceColumn: nome_loja

		annotation SummarizationSetBy = Automatic

	column Cidade
		dataType: string
		lineageTag: 616c8b44-e1db-43eb-ac72-d98786e32077
		summarizeBy: none
		sourceColumn: Cidade

		annotation SummarizationSetBy = Automatic

	column UF
		dataType: string
		lineageTag: 265e381d-f040-431c-9457-b0fa3ccf20c9
		summarizeBy: none
		sourceColumn: UF

		annotation SummarizationSetBy = Automatic

	partition lojas = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("C:\Users\Victor\Documents\Desktop\workspace\power bi 1\Power-Bi-project\bd_vendas.xlsx"), null, true),
				    lojas_Sheet = Fonte{[Item="lojas",Kind="Sheet"]}[Data],
				    #"Tipo Alterado" = Table.TransformColumnTypes(lojas_Sheet,{{"Column1", type text}, {"Column2", type text}, {"Column3", type text}, {"Column4", type text}}),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Tipo Alterado", [PromoteAllScalars=true]),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"codigo_loja", type text}, {"nome_loja", type text}, {"Cidade", type text}, {"UF", type text}})
				in
				    #"Tipo Alterado1"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

